In [2]:
import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First price:", prices[0])
print("Last price:", prices[-1])

First price: 199
Last price: 599


In [3]:
import numpy as np

scores = np.array([
    [45, 50, 60, 55, 70],
    [65, 75, 80, 72, 68],
    [55, 62, 58, 77, 85]
])

print(scores[:, 1:4])

[[50 60 55]
 [75 80 72]
 [62 58 77]]


In [4]:
import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

print(ratings[-3:])

[2.9 5.  3.5]


In [5]:
import numpy as np

numbers = np.arange(1, 21)

print(numbers[1::3])

[ 2  5  8 11 14 17 20]


In [6]:
import numpy as np

prices = np.array([250, 650, 450, 800, 550, 300, 750])

result = prices[prices > 500]

print(result)

[650 800 550 750]


In [7]:
import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print(indices[0])

[0 3 4]
