In [2]:
import numpy as np

prices = np.array([299, 499, 799, 0, 1599, -1, 899])

print(prices)
print(prices.dtype)

[ 299  499  799    0 1599   -1  899]
int64


In [3]:
positive_prices = prices[prices > 0]

average_price = positive_prices.mean()

prices[prices <= 0] = average_price

print(prices)

[ 299  499  799  819 1599  819  899]


In [4]:
quantities = np.array([2, 1, 3, 4, 2, 1, 5])

total_bill = prices * quantities

print(total_bill)

[ 598  499 2397 3276 3198  819 4495]


In [5]:
print("Minimum:", prices.min())
print("Maximum:", prices.max())
print("Average:", prices.mean())
print("Total:", prices.sum())
print("Total Bill:", total_bill.sum())

Minimum: 299
Maximum: 1599
Average: 819.0
Total: 5733
Total Bill: 15282


In [6]:
unique_prices = np.unique(prices)

print(unique_prices)
print("Number of unique prices:", len(unique_prices))

[ 299  499  799  819  899 1599]
Number of unique prices: 6
