In [2]:
import numpy as np

likes = np.array([120, 250, 180, 320, 450, 275, 390])

print("Array:", likes)
print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

Array: [120 250 180 320 450 275 390]
ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [3]:
import numpy as np

steps = np.array([[3000, 5000],
                  [4000, 6000],
                  [3500, 5500],
                  [4500, 6500],
                  [5000, 7000]])

print("Original array:")
print(steps)
print("Shape:", steps.shape)

one_d = steps.reshape(10)
print("\n1D array:")
print(one_d)
print("Shape:", one_d.shape)

two_d = one_d.reshape(5, 2)
print("\nBack to 2D array:")
print(two_d)
print("Shape:", two_d.shape)

Original array:
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 6500]
 [5000 7000]]
Shape: (5, 2)

1D array:
[3000 5000 4000 6000 3500 5500 4500 6500 5000 7000]
Shape: (10,)

Back to 2D array:
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 6500]
 [5000 7000]]
Shape: (5, 2)


In [4]:
import numpy as np

prices = np.array([[120, 150, 80, 200],
                   [90, 110, 175, 250],
                   [130, 160, 95, 220]])

print("Original array:")
print(prices)

ravel_array = prices.ravel()
print("\nUsing ravel():")
print(ravel_array)

flatten_array = prices.flatten()
print("\nUsing flatten():")
print(flatten_array)

# ravel() usually returns a view, while flatten() always returns a copy.
# Therefore, ravel() can be more memory efficient than flatten().

prices.resize(4, 3)
print("\nUsing resize():")
print(prices)

Original array:
[[120 150  80 200]
 [ 90 110 175 250]
 [130 160  95 220]]

Using ravel():
[120 150  80 200  90 110 175 250 130 160  95 220]

Using flatten():
[120 150  80 200  90 110 175 250 130 160  95 220]

Using resize():
[[120 150  80]
 [200  90 110]
 [175 250 130]
 [160  95 220]]


In [5]:
import numpy as np

playlist = np.array([[10, 5, 8],
                     [7, 12, 6],
                     [15, 9, 11]])

print("Original playlist:")
print(playlist)

transpose1 = playlist.T
print("\nUsing T:")
print(transpose1)

transpose2 = np.transpose(playlist)
print("\nUsing np.transpose():")
print(transpose2)

Original playlist:
[[10  5  8]
 [ 7 12  6]
 [15  9 11]]

Using T:
[[10  7 15]
 [ 5 12  9]
 [ 8  6 11]]

Using np.transpose():
[[10  7 15]
 [ 5 12  9]
 [ 8  6 11]]


In [6]:
import numpy as np

ratings = np.array([5, 4, 3, 5, 4,
                    2, 5, 3, 4, 5,
                    4, 3, 5, 2, 4])

print("Original 1D array:")
print(ratings)

ratings_2d = ratings.reshape(3, 5)
print("\n3x5 array:")
print(ratings_2d)

ratings_1d = ratings_2d.flatten()
print("\nBack to 1D array:")
print(ratings_1d)

# Use flatten() when you need an independent copy of the data.
# Use ravel() when you want a memory-efficient 1D view when possible.

Original 1D array:
[5 4 3 5 4 2 5 3 4 5 4 3 5 2 4]

3x5 array:
[[5 4 3 5 4]
 [2 5 3 4 5]
 [4 3 5 2 4]]

Back to 1D array:
[5 4 3 5 4 2 5 3 4 5 4 3 5 2 4]
