In [2]:
import numpy as np

zomato = np.array([4.5, 4.2, 3.8, 4.7, 4.0])
swiggy = np.array([4.1, 4.6, 3.9, 4.3, 4.8])

result = np.concatenate((zomato, swiggy))

print(result)

[4.5 4.2 3.8 4.7 4.  4.1 4.6 3.9 4.3 4.8]


In [3]:
import numpy as np

post1 = np.array([100, 120, 150, 130, 160, 180, 200])
post2 = np.array([80, 90, 110, 105, 125, 140, 155])
post3 = np.array([200, 220, 250, 270, 300, 320, 350])

result = np.vstack((post1, post2, post3))

print(result)

[[100 120 150 130 160 180 200]
 [ 80  90 110 105 125 140 155]
 [200 220 250 270 300 320 350]]


In [4]:
import numpy as np

product_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

parts = np.array_split(product_ids, 5)

for part in parts:
    print(part)
    print("Shape:", part.shape)

[101 102 103]
Shape: (3,)
[104 105 106]
Shape: (3,)
[107 108]
Shape: (2,)
[109 110]
Shape: (2,)
[111 112]
Shape: (2,)


In [5]:
import numpy as np

messages = np.array([
    [20, 25, 30, 22, 28, 35, 40],
    [10, 15, 12, 18, 20, 25, 30],
    [30, 35, 40, 38, 45, 50, 55]
])

new_user = np.array([15, 20, 18, 22, 25, 28, 30])

messages = np.insert(messages, 3, new_user, axis=0)

totals = np.sum(messages, axis=1)

least_user = np.argmin(totals)

messages = np.delete(messages, least_user, axis=0)

print(messages)

[[20 25 30 22 28 35 40]
 [30 35 40 38 45 50 55]
 [15 20 18 22 25 28 30]]


In [6]:
import numpy as np

views = np.array([100, 200, 300, 400, 500])

view_array = views.view()
copy_array = views.copy()

view_array[0] = 999
copy_array[0] = 888

print("Original:", views)
print("View:", view_array)
print("Copy:", copy_array)

Original: [999 200 300 400 500]
View: [999 200 300 400 500]
Copy: [888 200 300 400 500]
