In [3]:
import numpy as np

my_scores = np.array([5, 4, 3, 5, 4])
print(my_scores)

[5 4 3 5 4]


In [4]:
import numpy as np

even_numbers = np.arange(10, 31, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30]


In [5]:
import numpy as np

values = np.linspace(0, 1, 8)
print(values)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [6]:
import numpy as np

cart = np.zeros(10)
cart[2] = 1
cart[6] = 1
print(cart)

[0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]


In [7]:
import numpy as np

np.random.seed(42)
otp = np.random.randint(1000, 10000, 6)
print(otp)

[8270 1860 6390 6191 6734 7265]
