In [2]:
import numpy as np

teams = np.array(["CSK", "MI", "RCB", "MI", "CSK", "GT", "RCB"])
print(np.unique(teams))

['CSK' 'GT' 'MI' 'RCB']


In [3]:
import numpy as np

ratings = np.array([4.5, np.nan, 3.5, 5.0, np.nan, 4.0])
print(np.isnan(ratings).sum())

2


In [4]:
import numpy as np

prices = np.array([50, 250, 1200, 750, 1500, 500])
print(np.clip(prices, 100, 1000))

[ 100  250 1000  750 1000  500]


In [5]:
import numpy as np

views = np.array([1000, np.nan, 5000, np.inf, 2500, -np.inf])

max_value = np.nanmax(views[np.isfinite(views)])
views[np.isnan(views)] = 0
views[np.isinf(views)] = max_value

print(views)

[1000.    0. 5000. 5000. 2500. 5000.]


In [6]:
import numpy as np

numbers = np.array([10, 15, 22, 31, 40, 55, 68])

indices = np.where(numbers % 2 == 0)

print(indices)

(array([0, 2, 4, 6]),)
